name: WeakHashMap Code Validation and Testing
on:
  pull_request:
    branches: [ trunk ]
    types: [ opened, synchronize ]

jobs:
  run_apple_tests:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: gradle/actions/setup-gradle@v3
        name: Setup Gradle
      - name: Run MacOS Unit tests with Gradle wrapper
        run: ./gradlew :shared:macosArm64Test
  run_jvm_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: gradle/actions/setup-gradle@v3
        name: Setup Gradle
      - name: Run JVM unit tests with Gradle wrapper
        run: ./gradlew :shared:jvmTest